### ISSUE TITLE
如何让moran方案显示不完全双拼的候选词？

### ISSUE THREAD

**Issue by WzLYVg387U** [rimeinn/rime-moran#58]
以【模式】为例，惯常的双拼方案中键入 `mou` 后【模式】就会出现在首页候选词里，而看起来moran方案中会把 `u` 视作单字 `mo` 的首个形码，而不是词组中第二个字的首个音码，请问是否有办法可以解决这个问题？

**Comment by ksqsf** [comment]
要保留【整句直接辅助码】的话，因为技术原因，做不到。需要首先改成【间接辅助码】：

<img width="287" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/df2e516f-fc6e-422f-87a5-d0b8b702ca22">

此外，可以尝试【辅筛】模式。

<img width="274" alt="image" src="https://github.com/ksqsf/rime-moran/assets/23358293/9eef3b63-f91b-4675-814d-c8c246dc029a">

**Comment by ksqsf** [comment]
技术原因就是指 Rime 在 syllable 数量较多时简拼性能很差。这个在目前 librime 1.0 的框架下似乎无法解决。

**Comment by ksqsf** [comment]
可以这样做，类似于拼音的挂接用法，不过没有 `moran` 控制得那么精细。

```diff
--- a/moran_aux.schema.yaml
+++ b/moran_aux.schema.yaml
@@ -55,6 +55,7 @@ engine:
     - table_translator@custom_phrase       # 自定義短語
     #- table_translator@english             # 英語混輸
     #- table_translator@japanese            # 日語混輸
+    - table_translator@fixed
     - lua_translator@*moran_aux_translator
   filters:
     #- lua_filter@*moran_aux_hint           # 輔助碼提示需要去掉本行開頭的 # 符號
@@ -80,6 +81,13 @@ speller:
       - moran:/algebra/user_sentence_bottom?
       - moran:/algebra/user_force_bottom?
 
+fixed:
+  dictionary: moran_fixed
+  enable_completion: false
+  enable_sentence: false
+  enable_user_dict: false
+  initial_quality: 100
+
 translator:
   dictionary: moran.extended
   prism: moran_aux
```
